name: Linear Changeset Action
description: Action for linear changeset
author: Softnetics

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  # Required
  project-id:
    description: 'Project Id'
    required: true
  # Optional
  repository:
    description: 'Repository name'
    default: '${{ github.repository }}'
  token:
    description: 'GitHub token'
    default: '${{ github.token }}'
  max-attempts:
    description: 'Maximum number of attempts'
    default: '3'

  webhook-url:
    description: 'Release webhook URL'
    required: true

runs:
  using: node20
  main: dist/index.js
