name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  mode:
    description: 'Mode of operation'
    required: true
  token:
    description: 'GitHub token'
    default: '${{ github.token }}'
  release-tags:
    description: 'Release tags'
    required: true
  owner:
    description: 'Repository owner'
    default: '${{ github.repository_owner }}'
  repo:
    description: 'Repository name'
    default: '${{ github.repository }}'
  max-attempts:
    description: 'Maximum number of attempts'
    default: '3'
  release-webhook-url:
    description: 'Release webhook URL'
    required: true
  version:
    description: 'Version'
    required: true
  environment:
    description: 'Environment'
    required: true
  project-name:
    description: 'Project name'
    required: true

runs:
  using: node20
  main: dist/index.js
